# Настройки ORM
datasource:
  # Задаём базу данных, к которой будет происходить подключение
  db:
    username: ""
    password: ""
    url: "jdbc:h2:./petProject"

# Заполняем базу данных первоначальными данными
ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true
