datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: postgres
    password: bsDL4wbZGnXDjB3IByHu
    url: jdbc:postgresql://containers-us-west-147.railway.app:6231/railway

ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true
